<script lang="ts">
	import { IconInfoCircle } from '@tabler/icons-svelte';
</script>

<div class="api-doc">
	<h1>Managing API Keys</h1>
	<div class="api-callout"><div class="api-callout-icon"><IconInfoCircle size={30} stroke={2} /></div><div class="api-callout-content"><h3>For instructors and administrators</h3><p>Use this guide to manage course API-key access safely. Estimated reading time: 2–3 minutes.</p></div></div>
	<p class="api-doc-lead">The API Keys page lets administrators manage keys across Rocky without exposing secret key values.</p>

	<section class="api-doc-section"><h2>1. Review safe key information</h2><p>Full API key values are never displayed. The page shows only the key name, owner, course, status, and creation date. Do not include internal IDs, hashes, or secret values in screenshots or documentation.</p><img class="documentation-screenshot" src="/API-1.Full-Page.png" alt="The main administrative API Keys management view" /><p class="documentation-screenshot-caption">The main administrative API key view shows safe key-management information.</p></section>
	<section class="api-doc-section"><h2>2. Search and filter</h2><p>Search by owner, email, key name, or course. Combine the status, semester, and course filters as needed. Selecting a semester narrows the course list to that term. Use the sortable column headings when you need a different organization.</p><img class="documentation-screenshot" src="/API-2.Filter.png" alt="Search, status, semester, and course filters on the API Keys management page" /><p class="documentation-screenshot-caption">Filters can be combined before sorting the results.</p></section>
	<section class="api-doc-section"><h2>3. Sort and review keys</h2><p>Keys start with newer semesters first, then course and owner. Select the Semester, Course, Owner, Status, or Created column heading to sort; the active heading shows the sort direction.</p><p>The table includes selection, semester, owner, role or owner type, course, key name, status, created date, and actions. Group-owned keys may show a group identifier instead of a person’s name.</p></section>
	<section class="api-doc-section"><h2>4. Read status safely</h2><p>Active rows have a subtle green tint and inactive rows have a subtle red tint. The Active or Inactive badge remains visible, so status does not depend on color alone.</p><img class="documentation-screenshot" src="/API-4.Tint.png" alt="Active and inactive API key rows with visible status badges" /><p class="documentation-screenshot-caption">Row color supports the visible status badge rather than replacing it.</p></section>
	<section class="api-doc-section"><h2>5. Change key status</h2><p>Use <strong>Deactivate</strong> or <strong>Reactivate</strong> for one key and confirm the prompt. Prefer deactivation over permanent deletion when historical records may still refer to the key.</p></section>
	<section class="api-doc-section"><h2>6. Use bulk actions</h2><p>Select multiple keys or use the select-all checkbox for the visible filtered rows. Bulk deactivate and reactivate actions ask for confirmation. Use <strong>Clear selection</strong> to start over. Keys already in the requested state are skipped, and the completion message reports successes, failures, and skipped keys.</p><img class="documentation-screenshot" src="/API-6.BulkBar.png" alt="Bulk API key action toolbar with deactivate, reactivate, and clear selection controls" /><p class="documentation-screenshot-caption">Bulk actions apply only to the keys selected in the current filtered results.</p></section>
	<section class="api-doc-section"><h2>Recommended practices</h2><ul><li>Filter to the correct semester and course before bulk actions.</li><li>Confirm the owner and course before changing a key.</li><li>Deactivate keys that should no longer be usable.</li><li>Never copy or expose secret values.</li></ul></section>
</div>
