<script lang="ts">
	import { IconInfoCircle } from '@tabler/icons-svelte';
</script>

<div class="api-doc">
	<h1>User Management</h1>
	<div class="api-callout"><div class="api-callout-icon"><IconInfoCircle size={30} stroke={2} /></div><div class="api-callout-content"><h3>For instructors and administrators</h3><p>Use this guide to manage Rocky accounts. Estimated reading time: 2–3 minutes.</p></div></div>
	<p class="api-doc-lead">User Management helps administrators find accounts, review identity and status, update roles, and safely manage account access in bulk.</p>

	<section class="api-doc-section"><h2>1. Choose an account source</h2><p>Use <strong>Kent accounts</strong> to work with accounts using Kent email addresses. Use <strong>Whitelist accounts</strong> to review the separate approved-account list and add a whitelist entry when needed.</p><img class="documentation-screenshot" src="/UM-1.Acc-Source.png" alt="Kent accounts and Whitelist accounts tabs on the User Management page" /><p class="documentation-screenshot-caption">Administrators can switch between the two account sources.</p></section>
	<section class="api-doc-section"><h2>2. Search, filter, and sort</h2><p>Search by name or email, then combine the role, status, and course filters to narrow the list. The course filter uses actual course membership or instructor and teaching-assistant associations. Choose <strong>Name: A–Z</strong> or <strong>Name: Z–A</strong> to sort the filtered results; all controls can be combined.</p><img class="documentation-screenshot" src="/UM-2.Search-Filter.png" alt="Search, role, status, course, and name-sort controls on the User Management page" /><p class="documentation-screenshot-caption">Use the controls together to find the accounts you need.</p></section>
	<section class="api-doc-section"><h2>3. Review the user table</h2><p>The table shows a selection checkbox, name, email, role, status, and actions. Use the first checkbox to select all users currently visible after filtering.</p></section>
	<section class="api-doc-section"><h2>4. Update roles carefully</h2><p>Choose <strong>Student</strong>, <strong>Instructor</strong>, or <strong>Admin</strong> from the role dropdown. Rocky asks for confirmation before changing a role and provides feedback after the update. Verify the account identity before changing permissions.</p><img class="documentation-screenshot" src="/UM-4.Role-Dropdown.png" alt="Role dropdown with Student, Instructor, and Admin options" /><p class="documentation-screenshot-caption">Confirm the correct account before changing permissions.</p></section>
	<section class="api-doc-section"><h2>5. Activate, deactivate, and use bulk actions</h2><p><strong>Active</strong> accounts can use Rocky; <strong>Inactive</strong> accounts cannot. Use the row action to deactivate or reactivate one account. For several accounts, select rows, use the bulk toolbar, and confirm the change. Rocky reports updated accounts and any selected accounts that could not be found.</p><img class="documentation-screenshot" src="/UM-5.Bulk-Activate.png" alt="Selected user accounts and bulk activation controls on the User Management page" /><p class="documentation-screenshot-caption">Select rows or use select all before confirming a bulk activation or deactivation.</p></section>
	<section class="api-doc-section"><h2>Recommended practices</h2><ul><li>Verify a user’s identity before changing a role.</li><li>Avoid deactivating active instructors during a current term without confirmation.</li><li>Use filters before applying a bulk action.</li><li>Review the result message after each bulk operation.</li></ul></section>
</div>
